- name: functions
  hosts: local
  connection: local
  vars:
    technologies: DevOps, Linux, Shell, Ansible
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello {{ name | default('Mohit') }}" # Default variable if not defined

# Split string into list
  - name: Convert string to list
    ansible.builtin.set_fact:
      msg: "Technologies are: "{{ technologies | split(,) }}"