  - name: functions
    hosts: local
    connection: local
    vars:
      technologies: DevOps, Linux, Shell, Ansible # String variable
      # dictionary==map
      tags: # List variable
        Application: payment
        Environment: dev
      listTags: # List of maps
      - key: Application
        value: payment
      - key: dev
        value: Production
    tasks:
    - name: default variable
      ansible.builtin.debug:
        msg: "Hello {{ name | default('Mohit') }}" # Default variable if not defined

    # Split string into list
    - name: Convert string to list
      ansible.builtin.debug:
        msg: "Technologies are: {{ technologies | split(', ') }}"

    - name: Convert map to list
      ansible.builtin.debug:
        msg: "Tags are: {{ tags | dict2items }}"

    - name: Convert list into map
      ansible.builtin.debug:
        msg: "List Tags are: {{ listTags | items2dict }}"
    
    - name: read yaml and take it into the variable
      ansible.builtin.set_fact:
        student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

    - name: Convert yaml to json
      ansible.builtin.debug:
        msg: "Student info in json format: {{ student_yaml | to_nice_json }}"
    
    - name: Save json to file
      ansible.builtin.copy:
        content: "{{ student_yaml | to_nice_json }}"
        dest: "./student-data.json"